### ISSUE TITLE
merged with search functionality; check it out

### ISSUE THREAD

**Issue by kdudenas** [CS407/bookexchange#1]
I had a lot of conflicts to look at merging into release 1.0; mostly it was Book and Read. Book I think should be good now, I just had to change my edition String to int and include the Parcelable stuff. Read I'm slightly concerned that I accidentally erased something -- I think we both filled in functions and they ended up being on the same lines -- anyway if you could just check that out and lemme know it's not all broken that'd be great

**Comment by kdudenas** [comment]
update Read is broken but I'm on it

**Comment by kdudenas** [comment]
aight so two main differences:
1. I never got rid of the Seller-related stuff; that's fine, we ditched that.
2. my getBookSet() is way different from @shahsunny7 's; I didn't know you totally redid that or I would've had an easier time

**Comment by ssunny7** [comment]
Pulled all changes and fixed any merge conflicts I observed. All of them are fixed now, but it remains to be seen if the app is still working fine after all the merges.
